[pytest]
addopts = -p no:cacheprovider
testpaths = tests
norecursedirs = venv frontend node_modules dist __pycache__ pytest-cache-files-*
filterwarnings =
    ignore:websockets\.WebSocketClientProtocol is deprecated:DeprecationWarning
    ignore:websockets\.legacy is deprecated:DeprecationWarning
