"""add trade management fields

Revision ID: 2fee05e2d996
Revises: 69cdb0164f73
Create Date: 2026-03-15 17:28:26.467807
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '2fee05e2d996'
down_revision = '69cdb0164f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategies', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('INTRADAY', 'SCALP', 'SMA_CROSS', 'SMC_INTRADAY', name='strategy_name_enum', native_enum=False),
               existing_nullable=False)
    op.add_column('trades', sa.Column('is_be_reached', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('trades', sa.Column('last_swing_sl', sa.Numeric(precision=20, scale=8), nullable=True))
    op.alter_column('trades', 'tag',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('INTRADAY', 'SCALP', 'SMA_CROSS', 'SMC_INTRADAY', name='trade_tag_enum', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'tag',
               existing_type=sa.Enum('INTRADAY', 'SCALP', 'SMA_CROSS', 'SMC_INTRADAY', name='trade_tag_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('trades', 'last_swing_sl')
    op.drop_column('trades', 'is_be_reached')
    op.alter_column('strategies', 'name',
               existing_type=sa.Enum('INTRADAY', 'SCALP', 'SMA_CROSS', 'SMC_INTRADAY', name='strategy_name_enum', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
