"""add demo_balance and exit_price

Revision ID: 6d744a77c42f
Revises: c888b3e71cdb
Create Date: 2026-03-15 18:41:24.908005
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '6d744a77c42f'
down_revision = 'c888b3e71cdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('exit_price', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('users', sa.Column('demo_balance', sa.Numeric(precision=20, scale=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'demo_balance')
    op.drop_column('trades', 'exit_price')
    # ### end Alembic commands ###
