"""add is_demo field to trades

Revision ID: c888b3e71cdb
Revises: 2fee05e2d996
Create Date: 2026-03-15 17:50:52.851397
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c888b3e71cdb'
down_revision = '2fee05e2d996'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('is_demo', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'is_demo')
    # ### end Alembic commands ###
